# R for travis: see documentation at https://docs.travis-ci.com/user/languages/r

language: r

cache: packages

addons:
  apt:
    packages:
      - libproj-dev
      - libopenjpeg-dev
      - libjasper-dev
      - libpng-dev
      - zlib1g-dev

r_github_packages:
  - jimhester/covr

env:
  global:
    - MAKEFLAGS="j -2"

matrix:
  include:
    - env: ECCODES_VERSION=2.0.0
      sudo: required
      os: linux
      dist: xenial
      r_check_args: --as-cran
      before_install: ./install_eccodes.sh
    - env: ECCODES_VERSION=2.12.5
      sudo: required
      os: linux
      dist: xenial
      r_check_args: --as-cran
      before_install: ./install_eccodes.sh
    - env:
      - ECCODES_VERSION=2.0.0
      - OPENJPEG_INCLUDE_DIR=/usr/local/include/openjpeg-2.3
      latex: false
      sudo: required
      os: osx
      r_check_args: --as-cran
      before_install:
        - brew search eccodes
        - brew update
        # - brew outdated libpng || brew upgrade libpng
        # - brew outdated lzlib || brew upgrade lzlib
        # - brew outdated jpeg || brew upgrade jpeg
        # - brew install jasper
        # - brew install openjpeg
        - brew install eccodes
        # - ./install_eccodes.sh
    - env:
      - ECCODES_VERSION=2.12.5
      - OPENJPEG_INCLUDE_DIR=/usr/local/include/openjpeg-2.3
      latex: false
      sudo: required
      os: osx
      r_check_args: --as-cran
      before_install:
        - brew search eccodes
        - brew update
        # - brew outdated libpng || brew upgrade libpng
        # - brew outdated lzlib || brew upgrade lzlib
        # - brew outdated jpeg || brew upgrade jpeg
        # - brew install jasper
        # - brew install openjpeg
        - brew install eccodes
        # - ./install_eccodes.sh

after_success:
  - Rscript -e 'library(covr); codecov()'

warnings_are_errors: true

notifications:
  email:
    on_success: change
    on_failure: change