build: false

platform: x64

environment:
  matrix:
    - MINICONDA: C:\Miniconda3-x64
      MINICONDA_CHANNEL: conda-forge

init:
  - "ECHO %MINICONDA%"

install:
  - "set PATH=%MINICONDA%;%MINICONDA%\\Scripts;%PATH%"
  - conda config --set always_yes yes --set changeps1 no
  - conda update -q conda
  - conda info -a
  - "conda create -n win_gribr -c %MINICONDA_CHANNEL% r-base rtools eccodes r-proj4"
  - activate win_gribr
  - "echo %PATH%"
  - dir

build_script:
  - R CMD INSTALL --no-multiarch --clean .

test_script:
  - R CMD CHECK --as-cran
