build: false

platform: x64

environment:
  matrix:
    - MINICONDA: C:\Miniconda3-x64
      MINICONDA_CHANNEL: conda-forge

init:
  - "ECHO %MINICONDA%"

install:
  - "set PATH=%MINICONDA%\\Scripts;%PATH%"
  - conda config --set always_yes yes --set changeps1 no
  - conda update -q conda
  - "conda create -n win_gribr -c %MINICONDA_CHANNEL% r-base eccodes r-proj4 rtools r-covr r-lintr r-testthat pandoc"
  - activate win_gribr

build_script:
  - R CMD build --clean --no-multiarch .

test_script:
  - R CMD check --as-cran gribr_1.3.0.tar.gz
