build: false

platform: x64

environment:
  matrix:
    - MINICONDA: C:\Miniconda3-x64
      MINICONDA_CHANNEL: conda-forge
      CONDA_LIB: "%MINICONDA%\\Library\\lib"
      CONDA_INC: "%MINICONDA%\\Library\\include"
      CONDA_BIN: "%MINICONDA%\\Library\\bin"

init:
  - "ECHO %MINICONDA%"
  - "ECHO %CONDA_INC%"
  - "ECHO %CONDA_LIB%"

install:
  - "set PATH=%CONDA_BIN%;%MINICONDA%\\Scripts;%PATH%"
  - conda config --set always_yes yes --set changeps1 no
  - conda update -q conda
  - "conda install -c %MINICONDA_CHANNEL% r-base eccodes r-proj4 rtools"

build_script:
  - R CMD INSTALL --no-multiarch --clean --configure-vars="PKG_LIBS=-L%CONDA_LIB PKG_CPPFLAGS=-I%CONDA_INC%" .

test_script:
  - R CMD CHECK --as-cran
